ALTER TABLE playlist_resource RENAME resourcelist_id  TO resources_id;


        
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE
-- DEPLOYED - DO NOT USE THIS FILE ANYMORE