ALTER TABLE urlresource
   ALTER COLUMN name DROP NOT NULL;

   
   
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
-- EXECUTED IN PROD - DO NOT ALTER THIS FILE
